### ISSUE TITLE
提供的链接无法正常下载

### ISSUE THREAD

**Issue by amokiel** [jorry-yun/GenshinTool#1]
希望提供可以正常下载的链接，多谢

**Comment by jorry-yun** [comment]
可能是github将下载链接屏蔽了，你尝试右键蓝色字体，复制链接地址，新开浏览器标签页，粘贴访问，如若依然无法下载，可以在目录 安装包/xxx.apk 下载

**Comment by amokiel** [comment]
> 可能是github将下载链接屏蔽了，你尝试右键蓝色字体，复制链接地址，新开浏览器标签页，粘贴访问，如若依然无法下载，可以在目录 安装包/xxx.apk 下载

多谢你，已经在目录找到安装好了
